### PR TITLE
providing a faster transform_tau method if topologies are given in list

### PR DESCRIPTION
**Pull request by marota**
For the implemented test to pass, this supposes that https://github.com/BDonnot/leap_net/issues/11 is also integrated in the leapNet package. This passes in local with the proposed modifications

def _given_list_topo_encode(self, obs):
        res = np.zeros(self.nb_diff_topo)
        # retrieve the topology
        topo_vect = 1 * obs.topo_vect

        # and now put the right number
        for sub_id in range(obs.n_sub):
            # TODO there might be a way to optimize that, but what for ?
            beg_, end_ = self.subs_index[sub_id]
            this_sub_topo = topo_vect[beg_:end_]
            disco = this_sub_topo == -1
            conn = ~disco
            if np.all(this_sub_topo[conn] == 2) or np.all(this_sub_topo[conn] == 1):
                # complete / reference topology, so i don't do anything
                continue

            # so i have a different topology that the reference one
            #lookup = (sub_id, tuple([el if el >= 1 else 1 for el in this_sub_topo]))
            topo_found=False

            if (np.all(conn)):
                lookup = (sub_id, tuple([el if el >= 1 else 1 for el in this_sub_topo]))
                if lookup in self.dict_topo:
                    res[self.dict_topo[lookup]] = 1.
                    topo_found = True
            else:
                for topo_sub in self.dict_topo:
                    if topo_sub[0] == sub_id:
                        topo=np.array(topo_sub[1])
                        if np.all(topo[conn]==this_sub_topo[conn]):
                            res[self.dict_topo[topo_sub]] = 1.
                            topo_found=True
                            conn_elements_bus_bar_2=conn[(topo_found==2)]
                            break

            #if lookup in self.dict_topo:
            #    res[self.dict_topo[lookup]] = 1.
            #else:
            if not topo_found:
                warnings.warn(f"Topology {lookup} is not found on the topo dictionary")
        return res

### CODE REVIEW

**Comment by Mleyliabadi** [comment]
I don't think that the file `Test_extract_tau.py` is in the right place! It should be in `tests` folder, [here](https://github.com/Mleyliabadi/LIPS/tree/main/lips/tests). You can create a folder for augmented simulators in `tests` directory such as `tests/augmented_simulators` and put the file there.

**Comment by Mleyliabadi** [comment]
The assertion is failed during the test. 

CircleCI output for the test: 

```command
>       assert np.all(extract_tau_1[1].astype((np.bool_))==extract_tau_bis[1])
E       assert False
E        +  where False = <function all at 0x7f36c214a3a0>(array([[False...True, False]]) == array([[0, 0,...], dtype=int8)
E        +    where <function all at 0x7f36c214a3a0> = np.all
E           Use -v to get the full diff)

lips/tests/test_leap_net.py:138: AssertionError

```

**Comment by marota** [comment]
> The assertion is failed during the test.
> 
> CircleCI output for the test:
> 
> ```shell
> >       assert np.all(extract_tau_1[1].astype((np.bool_))==extract_tau_bis[1])
> E       assert False
> E        +  where False = <function all at 0x7f36c214a3a0>(array([[False...True, False]]) == array([[0, 0,...], dtype=int8)
> E        +    where <function all at 0x7f36c214a3a0> = np.all
> E           Use -v to get the full diff)
> 
> lips/tests/test_leap_net.py:138: AssertionError
> ```

Yes that is expected given the current version of leapnet package, see initial comment

**Comment by Mleyliabadi** [comment]
> > The assertion is failed during the test.
> > CircleCI output for the test:
> > ```shell
> > >       assert np.all(extract_tau_1[1].astype((np.bool_))==extract_tau_bis[1])
> > E       assert False
> > E        +  where False = <function all at 0x7f36c214a3a0>(array([[False...True, False]]) == array([[0, 0,...], dtype=int8)
> > E        +    where <function all at 0x7f36c214a3a0> = np.all
> > E           Use -v to get the full diff)
> > 
> > lips/tests/test_leap_net.py:138: AssertionError
> > ```
> 
> Yes that is expected given the current version of leapnet package, see initial comment

OK, so I will wait until this feature is added in LeapNet package before merging.

**Comment by Mleyliabadi** [comment]
It has been integrated by merging first into `ml-wip-upgrade-tests` where all the packages are updated to their last version and the resulted PR is merged into `main`. 

All the tests are passed. Closed !

**Comment by Mleyliabadi** [comment]
You can remove this branch (`am_accleratedTauTransform`) after the verification of the `main` branch. If all the required modification are present.

**Pull request closed without merging**
